[tool.poetry]
package-mode = false
name = "proj-a"

[tool.poetry.dependencies]
python = "^3.11"
server_schemas = {path = "../../libs/server_schemas", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
